import type { Metadata } from "next";
import { createClient } from "~/utils/supabase/server";
import { Providers } from "./providers";
import { Navigation } from "./components/navigation";

import "./globals.css";

export const metadata: Metadata = {
  title: "Next Auth",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <>
            <Navigation user={user} />
            {children}
          </>
        </Providers>
      </body>
    </html>
  );
}
