import type { Metadata } from "next";
import { Providers } from "./providers";
import { Navigation } from "./components/navigation";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App123",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <>
            <Navigation />
            {children}
          </>
        </Providers>
      </body>
    </html>
  );
}
